In [ ]:
import pandas as pd

In [12]:
import pandas as pd

data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Marketing-Data-Analysis..xlsx')

data.head()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,DO NOT MODIFY — preserved exactly as supplied ...,NaN,NaN,NaN,NaN,NaN,NaN
1,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
2,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
3,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
4,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100

In [13]:
data

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,DO NOT MODIFY — preserved exactly as supplied ...,NaN,NaN,NaN,NaN,NaN,NaN
1,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
2,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
3,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
4,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100
...,...,...,...,...,...,...,...
297,CMP0277,2025-03-04 00:00:00,Social Media,Baidoa,3342.91,599,124
298,CMP0006,2025-12-16 00:00:00,Social Media,Mogadishu,2877.39,463,NaN
299,CMP0226,2025-03-11 00:00:00,Radio,Bosaso,3509.09,714,42
300,CMP0209,2026-07-12 00:00:00,Email,Hargeisa,3794.91,442,77
301,CMP0037,2025-08-18 00:00:00,Influencer,NaN,4177.41,427,69

In [14]:
data.head()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,DO NOT MODIFY — preserved exactly as supplied ...,NaN,NaN,NaN,NaN,NaN,NaN
1,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
2,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
3,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
4,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100

In [15]:
data.tail()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
297,CMP0277,2025-03-04 00:00:00,Social Media,Baidoa,3342.91,599,124
298,CMP0006,2025-12-16 00:00:00,Social Media,Mogadishu,2877.39,463,NaN
299,CMP0226,2025-03-11 00:00:00,Radio,Bosaso,3509.09,714,42
300,CMP0209,2026-07-12 00:00:00,Email,Hargeisa,3794.91,442,77
301,CMP0037,2025-08-18 00:00:00,Influencer,NaN,4177.41,427,69

Number of rows and columns

In [16]:
data.shape

(302, 7)

Column names

In [17]:
data.columns

Index(['RAW DATA — 20_Marketing (Original Source)', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

Information about data

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 7 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   RAW DATA — 20_Marketing (Original Source)  287 non-null    object
 1   Unnamed: 1                                 286 non-null    object
 2   Unnamed: 2                                 285 non-null    object
 3   Unnamed: 3                                 286 non-null    object
 4   Unnamed: 4                                 286 non-null    object
 5   Unnamed: 5                                 280 non-null    object
 6   Unnamed: 6                                 286 non-null    object
dtypes: object(7)
memory usage: 16.6+ KB

Statistical summary

In [19]:
data.describe()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
count,287,286,285,286,286.00,280,286
unique,279,213,9,11,279.00,240,153
top,CMP0199,2026-06-03 00:00:00,Search,Mogadishu,3453.41,350,32
freq,2,4,84,92,2.00,4,6

Select one column

11 — Select multiple columns

In [22]:
data.columns

Index(['RAW DATA — 20_Marketing (Original Source)', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

In [23]:
print(data.columns.tolist())

['RAW DATA — 20_Marketing (Original Source)', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6']

In [24]:
data.isnull().sum()

RAW DATA — 20_Marketing (Original Source)    15
Unnamed: 1                                   16
Unnamed: 2                                   17
Unnamed: 3                                   16
Unnamed: 4                                   16
Unnamed: 5                                   22
Unnamed: 6                                   16
dtype: int64

In [25]:
data.duplicated().sum()

np.int64(7)

In [26]:
data[data.duplicated()]

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
72,CMP0083,2026-03-19 00:00:00,Search,Garowe,2263.59,309,69
216,CMP0074,2025-06-22 00:00:00,Influencer,Hargeisa,2615.82,529,102
230,CMP0151,2026-07-12 00:00:00,Radio,Mogadishu,3332.51,781,107
242,CMP0115,2025-06-10 00:00:00,Search,Bosaso,3832.39,350,100
253,CMP0179,2026-05-02 00:00:00,Search,Garowe,2086.02,273,88
277,CMP0058,2025-03-12 00:00:00,Radio,Kismayo,1656.74,182,12
285,CMP0235,2025-02-13 00:00:00,Search,Hargeisa,3453.41,860,230

In [28]:
data = data.drop_duplicates()

In [29]:
data.dtypes

RAW DATA — 20_Marketing (Original Source)    object
Unnamed: 1                                   object
Unnamed: 2                                   object
Unnamed: 3                                   object
Unnamed: 4                                   object
Unnamed: 5                                   object
Unnamed: 6                                   object
dtype: object

In [33]:
data.isnull().sum()

RAW DATA — 20_Marketing (Original Source)    15
Unnamed: 1                                   16
Unnamed: 2                                   17
Unnamed: 3                                   16
Unnamed: 4                                   16
Unnamed: 5                                   22
Unnamed: 6                                   16
dtype: int64

In [35]:
data.head()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,DO NOT MODIFY — preserved exactly as supplied ...,NaN,NaN,NaN,NaN,NaN,NaN
1,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
2,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
3,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
4,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100