In [ ]:
#import library pandan
#syntax for import (import library name as pd)
import pandas as pd

In [ ]:
#read data from google colab
data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/nimca.pptx (9)).xlsx")

In [ ]:
data.head()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,DO NOT MODIFY — preserved exactly as supplied ...,NaN,NaN,NaN,NaN,NaN,NaN
1,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
2,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
3,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
4,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100

Reading last five rows using tail function

In [ ]:
data.tail()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
297,CMP0277,2025-03-04 00:00:00,Social Media,Baidoa,3342.91,599,124
298,CMP0006,2025-12-16 00:00:00,Social Media,Mogadishu,2877.39,463,NaN
299,CMP0226,2025-03-11 00:00:00,Radio,Bosaso,3509.09,714,42
300,CMP0209,2026-07-12 00:00:00,Email,Hargeisa,3794.91,442,77
301,CMP0037,2025-08-18 00:00:00,Influencer,NaN,4177.41,427,69

In [ ]:
data.sample()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
103,CMP0215,2025-09-16 00:00:00,Email,Hargeisa,4603.44,1005,178

Data columns

In [ ]:
data.columns

Index(['RAW DATA — 20_Marketing (Original Source)', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

this diply data type

In [ ]:
data.dtypes

RAW DATA — 20_Marketing (Original Source)    object
Unnamed: 1                                   object
Unnamed: 2                                   object
Unnamed: 3                                   object
Unnamed: 4                                   object
Unnamed: 5                                   object
Unnamed: 6                                   object
dtype: object

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 7 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   RAW DATA — 20_Marketing (Original Source)  287 non-null    object
 1   Unnamed: 1                                 286 non-null    object
 2   Unnamed: 2                                 285 non-null    object
 3   Unnamed: 3                                 286 non-null    object
 4   Unnamed: 4                                 286 non-null    object
 5   Unnamed: 5                                 280 non-null    object
 6   Unnamed: 6                                 286 non-null    object
dtypes: object(7)
memory usage: 16.6+ KB

Disply  the discrip of statistics using discrib function

In [ ]:
data.describe()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
count,287,286,285,286,286.00,280,286
unique,279,213,9,11,279.00,240,153
top,CMP0199,2026-06-03 00:00:00,Search,Mogadishu,3453.41,350,32
freq,2,4,84,92,2.00,4,6

In [ ]:
data.describe(include="all")

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
count,287,286,285,286,286.00,280,286
unique,279,213,9,11,279.00,240,153
top,CMP0199,2026-06-03 00:00:00,Search,Mogadishu,3453.41,350,32
freq,2,4,84,92,2.00,4,6

In [ ]:
data.isnull().sum()

RAW DATA — 20_Marketing (Original Source)    15
Unnamed: 1                                   16
Unnamed: 2                                   17
Unnamed: 3                                   16
Unnamed: 4                                   16
Unnamed: 5                                   22
Unnamed: 6                                   16
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(7)

In [ ]:
print("Data Info After Cleaning:")
data.info()

print("\nMissing Values:")
print(data.isnull().sum())

print("\nDuplicate Rows:")
print(data.duplicated().sum())

Data Info After Cleaning:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 7 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   RAW DATA — 20_Marketing (Original Source)  287 non-null    object
 1   Unnamed: 1                                 286 non-null    object
 2   Unnamed: 2                                 285 non-null    object
 3   Unnamed: 3                                 286 non-null    object
 4   Unnamed: 4                                 286 non-null    object
 5   Unnamed: 5                                 280 non-null    object
 6   Unnamed: 6                                 286 non-null    object
dtypes: object(7)
memory usage: 16.6+ KB

Missing Values:
RAW DATA — 20_Marketing (Original Source)    15
Unnamed: 1                                   16
Unnamed: 2                                   17
Unnamed: 3                                   16
Unnamed: 4                                   16
Unnamed: 5                                   22
Unnamed: 6                                   16
dtype: int64

Duplicate Rows:
7

In [ ]:
data.head(10)

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,DO NOT MODIFY — preserved exactly as supplied ...,NaN,NaN,NaN,NaN,NaN,NaN
1,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
2,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
3,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
4,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100
5,NaN,2025-12-14 00:00:00,Social Media,Kismayo,3036.06,350,61
6,CMP0089,2025-03-16 00:00:00,Social Media,Hargeisa,4857.89,742,131
7,CMP0098,2025-04-25 00:00:00,Influencer,NaN,2904.04,2013,81
8,CMP0206,2026-06-12 00:00:00,Search,Garowe,518.97,101,20
9,CMP0094,2026-05-04 00:00:00,Influencer,Hargeisa,3151.53,510,74

In [ ]:
data = pd.read_excel(
    "/content/drive/MyDrive/Colab Notebooks/nimca.pptx (9)).xlsx",
    header=1
)

In [ ]:
data.head()

,DO NOT MODIFY — preserved exactly as supplied by the lecturer.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
1,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
2,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
3,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100
4,NaN,2025-12-14 00:00:00,Social Media,Kismayo,3036.06,350,61

In [ ]:
data.columns

Index(['DO NOT MODIFY — preserved exactly as supplied by the lecturer.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 7 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   DO NOT MODIFY — preserved exactly as supplied by the lecturer.  286 non-null    object
 1   Unnamed: 1                                                      286 non-null    object
 2   Unnamed: 2                                                      285 non-null    object
 3   Unnamed: 3                                                      286 non-null    object
 4   Unnamed: 4                                                      286 non-null    object
 5   Unnamed: 5                                                      280 non-null    object
 6   Unnamed: 6                                                      286 non-null    object
dtypes: object(7)
memory usage: 16.6+ KB

In [ ]:
data = pd.read_excel(
    "/content/drive/MyDrive/Colab Notebooks/Marketing-Data-Analysis..xlsx",
    header=1
)

In [ ]:
data.head()

,DO NOT MODIFY — preserved exactly as supplied by the lecturer.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
1,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
2,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
3,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100
4,NaN,2025-12-14 00:00:00,Social Media,Kismayo,3036.06,350,61

In [ ]:
data.tail()

,DO NOT MODIFY — preserved exactly as supplied by the lecturer.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
296,CMP0277,2025-03-04 00:00:00,Social Media,Baidoa,3342.91,599,124
297,CMP0006,2025-12-16 00:00:00,Social Media,Mogadishu,2877.39,463,NaN
298,CMP0226,2025-03-11 00:00:00,Radio,Bosaso,3509.09,714,42
299,CMP0209,2026-07-12 00:00:00,Email,Hargeisa,3794.91,442,77
300,CMP0037,2025-08-18 00:00:00,Influencer,NaN,4177.41,427,69

In [ ]:
data.shape

(301, 7)

In [ ]:
data.columns

Index(['DO NOT MODIFY — preserved exactly as supplied by the lecturer.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 7 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   DO NOT MODIFY — preserved exactly as supplied by the lecturer.  286 non-null    object
 1   Unnamed: 1                                                      286 non-null    object
 2   Unnamed: 2                                                      285 non-null    object
 3   Unnamed: 3                                                      286 non-null    object
 4   Unnamed: 4                                                      286 non-null    object
 5   Unnamed: 5                                                      280 non-null    object
 6   Unnamed: 6                                                      286 non-null    object
dtypes: object(7)
memory usage: 16.6+ KB