In [51]:
#import library pandan
#syntax for import (import library name as pd)
import pandas as pd

In [52]:
#read data from google colab
data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/nimca.pptx (9)).xlsx")

In [53]:
data.head()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,DO NOT MODIFY — preserved exactly as supplied ...,NaN,NaN,NaN,NaN,NaN,NaN
1,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
2,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
3,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
4,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100

Reading last five rows using tail function

In [54]:
data.tail()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
297,CMP0277,2025-03-04 00:00:00,Social Media,Baidoa,3342.91,599,124
298,CMP0006,2025-12-16 00:00:00,Social Media,Mogadishu,2877.39,463,NaN
299,CMP0226,2025-03-11 00:00:00,Radio,Bosaso,3509.09,714,42
300,CMP0209,2026-07-12 00:00:00,Email,Hargeisa,3794.91,442,77
301,CMP0037,2025-08-18 00:00:00,Influencer,NaN,4177.41,427,69

In [55]:
data.sample()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
85,CMP0086,2025-09-10 00:00:00,Search,Mogadishu,1245.05,135,28

Data columns

In [56]:
data.columns

Index(['RAW DATA — 20_Marketing (Original Source)', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

this diply data type

In [57]:
data.dtypes

RAW DATA — 20_Marketing (Original Source)    object
Unnamed: 1                                   object
Unnamed: 2                                   object
Unnamed: 3                                   object
Unnamed: 4                                   object
Unnamed: 5                                   object
Unnamed: 6                                   object
dtype: object

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 7 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   RAW DATA — 20_Marketing (Original Source)  287 non-null    object
 1   Unnamed: 1                                 286 non-null    object
 2   Unnamed: 2                                 285 non-null    object
 3   Unnamed: 3                                 286 non-null    object
 4   Unnamed: 4                                 286 non-null    object
 5   Unnamed: 5                                 280 non-null    object
 6   Unnamed: 6                                 286 non-null    object
dtypes: object(7)
memory usage: 16.6+ KB

Disply  the discrip of statistics using discrib function

In [59]:
data.describe()

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
count,287,286,285,286,286.00,280,286
unique,279,213,9,11,279.00,240,153
top,CMP0199,2026-06-03 00:00:00,Search,Mogadishu,3453.41,350,32
freq,2,4,84,92,2.00,4,6

In [60]:
data.describe(include="all")

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
count,287,286,285,286,286.00,280,286
unique,279,213,9,11,279.00,240,153
top,CMP0199,2026-06-03 00:00:00,Search,Mogadishu,3453.41,350,32
freq,2,4,84,92,2.00,4,6

In [61]:
data.isnull().sum()

RAW DATA — 20_Marketing (Original Source)    15
Unnamed: 1                                   16
Unnamed: 2                                   17
Unnamed: 3                                   16
Unnamed: 4                                   16
Unnamed: 5                                   22
Unnamed: 6                                   16
dtype: int64

In [62]:
data.duplicated().sum()

np.int64(7)

In [63]:
print("Data Info After Cleaning:")
data.info()

print("\nMissing Values:")
print(data.isnull().sum())

print("\nDuplicate Rows:")
print(data.duplicated().sum())

Data Info After Cleaning:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 7 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   RAW DATA — 20_Marketing (Original Source)  287 non-null    object
 1   Unnamed: 1                                 286 non-null    object
 2   Unnamed: 2                                 285 non-null    object
 3   Unnamed: 3                                 286 non-null    object
 4   Unnamed: 4                                 286 non-null    object
 5   Unnamed: 5                                 280 non-null    object
 6   Unnamed: 6                                 286 non-null    object
dtypes: object(7)
memory usage: 16.6+ KB

Missing Values:
RAW DATA — 20_Marketing (Original Source)    15
Unnamed: 1                                   16
Unnamed: 2                                   17
Unnamed: 3                                   16
Unnamed: 4                                   16
Unnamed: 5                                   22
Unnamed: 6                                   16
dtype: int64

Duplicate Rows:
7

In [64]:
data.head(10)

,RAW DATA — 20_Marketing (Original Source),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,DO NOT MODIFY — preserved exactly as supplied ...,NaN,NaN,NaN,NaN,NaN,NaN
1,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
2,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
3,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
4,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100
5,NaN,2025-12-14 00:00:00,Social Media,Kismayo,3036.06,350,61
6,CMP0089,2025-03-16 00:00:00,Social Media,Hargeisa,4857.89,742,131
7,CMP0098,2025-04-25 00:00:00,Influencer,NaN,2904.04,2013,81
8,CMP0206,2026-06-12 00:00:00,Search,Garowe,518.97,101,20
9,CMP0094,2026-05-04 00:00:00,Influencer,Hargeisa,3151.53,510,74

In [65]:
data = pd.read_excel(
    "/content/drive/MyDrive/Colab Notebooks/nimca.pptx (9)).xlsx",
    header=1
)

In [66]:
data.head()

,DO NOT MODIFY — preserved exactly as supplied by the lecturer.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
1,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
2,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
3,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100
4,NaN,2025-12-14 00:00:00,Social Media,Kismayo,3036.06,350,61

In [67]:
data.columns

Index(['DO NOT MODIFY — preserved exactly as supplied by the lecturer.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6'],
      dtype='object')

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 7 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   DO NOT MODIFY — preserved exactly as supplied by the lecturer.  286 non-null    object
 1   Unnamed: 1                                                      286 non-null    object
 2   Unnamed: 2                                                      285 non-null    object
 3   Unnamed: 3                                                      286 non-null    object
 4   Unnamed: 4                                                      286 non-null    object
 5   Unnamed: 5                                                      280 non-null    object
 6   Unnamed: 6                                                      286 non-null    object
dtypes: object(7)
memory usage: 16.6+ KB

In [69]:
data = pd.read_excel(
    "/content/drive/MyDrive/Colab Notebooks/Marketing-Data-Analysis..xlsx",
    header=1
)

In [70]:
data.head()

,DO NOT MODIFY — preserved exactly as supplied by the lecturer.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
1,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.8,258,58
2,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
3,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100
4,NaN,2025-12-14 00:00:00,Social Media,Kismayo,3036.06,350,61

In [71]:
data.tail()

,DO NOT MODIFY — preserved exactly as supplied by the lecturer.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
296,CMP0277,2025-03-04 00:00:00,Social Media,Baidoa,3342.91,599,124
297,CMP0006,2025-12-16 00:00:00,Social Media,Mogadishu,2877.39,463,NaN
298,CMP0226,2025-03-11 00:00:00,Radio,Bosaso,3509.09,714,42
299,CMP0209,2026-07-12 00:00:00,Email,Hargeisa,3794.91,442,77
300,CMP0037,2025-08-18 00:00:00,Influencer,NaN,4177.41,427,69

In [72]:
data.shape

(301, 7)

In [73]:
data.columns

Index(['DO NOT MODIFY — preserved exactly as supplied by the lecturer.',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6'],
      dtype='object')

In [74]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 7 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   DO NOT MODIFY — preserved exactly as supplied by the lecturer.  286 non-null    object
 1   Unnamed: 1                                                      286 non-null    object
 2   Unnamed: 2                                                      285 non-null    object
 3   Unnamed: 3                                                      286 non-null    object
 4   Unnamed: 4                                                      286 non-null    object
 5   Unnamed: 5                                                      280 non-null    object
 6   Unnamed: 6                                                      286 non-null    object
dtypes: object(7)
memory usage: 16.6+ KB

In [75]:
import pandas as pd

In [77]:
data=pd.read_excel("/content/Excel data.xlsx")

In [78]:
data.head()

,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
0,CMP0268,2026-02-24 00:00:00,Search,Mogadishu,1902.80,258,58
1,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
2,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100
3,NaN,2025-12-14 00:00:00,Social Media,Kismayo,3036.06,350,61
4,CMP0089,2025-03-16 00:00:00,Social Media,Hargeisa,4857.89,742,131

In [80]:
data.rename(columns={"old_column_name": "new_column_name"}, inplace=True)

In [81]:
data.rename(columns={"colum": "column"}, inplace=True)

In [82]:
old_value = "colum"
new_value = "column"

data.rename(columns={old_value: new_value}, inplace=True)

In [84]:
data.columns

Index(['Campaign_ID', 'Start_Date', 'Channel', 'Region', 'Budget', 'Leads',
       'Conversions'],
      dtype='object')

In [90]:
columns=["student_ID"]

In [91]:
data.isnull().sum()

Campaign_ID    15
Start_Date     15
Channel        16
Region         15
Budget         15
Leads          21
Conversions    15
dtype: int64

In [92]:
data[data.isnull().any(axis=1)]

,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
1,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
2,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100
3,NaN,2025-12-14 00:00:00,Social Media,Kismayo,3036.06,350,61
5,CMP0098,2025-04-25 00:00:00,Influencer,NaN,2904.04,2013,81
11,CMP0082,2025-08-19 00:00:00,Search,NaN,4275.45,604,169
...,...,...,...,...,...,...,...
287,CMP0012,2025-05-25 00:00:00,Social Media,NaN,2109.18,251,34
290,CMP0222,2026-07-23 00:00:00,Radio,Mogadishu,609.81,NaN,4
291,CMP0142,2025-06-23 00:00:00,Social Media,NaN,4216.83,508,70
296,CMP0006,2025-12-16 00:00:00,Social Media,Mogadishu,2877.39,463,NaN
299,CMP0037,2025-08-18 00:00:00,Influencer,NaN,4177.41,427,69

In [93]:
data[data.isnull().any(axis=1)]

,Campaign_ID,Start_Date,Channel,Region,Budget,Leads,Conversions
1,CMP0077,2026-06-13 00:00:00,NaN,Mogadishu,2408.15,408,89
2,CMP0207,2026-05-11 00:00:00,NaN,Kismayo,2635.33,573,100
3,NaN,2025-12-14 00:00:00,Social Media,Kismayo,3036.06,350,61
5,CMP0098,2025-04-25 00:00:00,Influencer,NaN,2904.04,2013,81
11,CMP0082,2025-08-19 00:00:00,Search,NaN,4275.45,604,169
...,...,...,...,...,...,...,...
287,CMP0012,2025-05-25 00:00:00,Social Media,NaN,2109.18,251,34
290,CMP0222,2026-07-23 00:00:00,Radio,Mogadishu,609.81,NaN,4
291,CMP0142,2025-06-23 00:00:00,Social Media,NaN,4216.83,508,70
296,CMP0006,2025-12-16 00:00:00,Social Media,Mogadishu,2877.39,463,NaN
299,CMP0037,2025-08-18 00:00:00,Influencer,NaN,4177.41,427,69

In [94]:
data.isnull().sum().sum()

np.int64(112)

In [97]:
data.dtypes

Campaign_ID     object
Start_Date      object
Channel         object
Region          object
Budget         float64
Leads           object
Conversions     object
dtype: object

In [102]:
data['Start_Date'] =pd.to_datetime(data['Start_Date'], errors='coerce')

In [107]:
data['Budget'] =pd.to_numeric(data['Budget'], errors='coerce')

In [108]:
data.dtypes

Campaign_ID     object
Start_Date       int64
Channel         object
Region          object
Budget         float64
Leads           object
Conversions     object
dtype: object

In [ ]:
data